# Introduction to NumPy

In [3]:
import numpy as np 

# Creating Arrays

>From python lists

In [4]:
np.array([1, 5, 4, 9])

array([1, 5, 4, 9])

> Explicitly set datatype

In [7]:
np.array([1, 5, 4, 9], dtype='float32')

array([1., 5., 4., 9.], dtype=float32)

> Multidimensional from list of lists

In [8]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

> Arrays of zeros and ones, or constant

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

> Fill with arbitrary number

In [19]:
np.full((3,3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

> Linear sequence

In [22]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# NumPy Array Attributes

In [23]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [24]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [25]:
x1

array([5, 0, 3, 3, 7, 9])

In [26]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [36]:
for (index, array) in enumerate([x1,x2,x3]):
    print(f"x{index}")
    print(f"\t ndim: {array.ndim}")
    print(f"\t shape: {array.shape}")
    print(f"\t size: {array.size}")
    print(f"\t dtype: {array.dtype}")
    print(f"\t item size: {array.itemsize}")
    print(f"\t total size: {array.nbytes}")

x0
	 ndim: 1
	 shape: (6,)
	 size: 6
	 dtype: int64
	 item size: 8
	 total size: 48
x1
	 ndim: 2
	 shape: (3, 4)
	 size: 12
	 dtype: int64
	 item size: 8
	 total size: 96
x2
	 ndim: 3
	 shape: (3, 4, 5)
	 size: 60
	 dtype: int64
	 item size: 8
	 total size: 480


# Indexing Arrays

In [37]:
x1

array([5, 0, 3, 3, 7, 9])

In [41]:
x1[0], x1[-1]

(5, 9)

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [47]:
x2[2,1], x2[-1,-4]

(6, 1)

In [46]:
x2[2,1]

6

In [48]:
x2[-1,-1] = 9

In [49]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 9]])

>[!attention] NumPy arrays are fixed type so conversion may be necessary

# Slicing arrays

>[!warning] Slices are views, so you may or may not want to `.copy()`

>Basic syntax
>`x[start:stop:step]`

In [50]:
x = np.arange(10)

In [53]:
x[:5], x[5:], x[2:4]

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([2, 3]))

In [54]:
x[::2], x[3::2]

(array([0, 2, 4, 6, 8]), array([3, 5, 7, 9]))

In [58]:
x[::-2], x[-5::-2], x[-5::2]

(array([9, 7, 5, 3, 1]), array([5, 3, 1]), array([5, 7, 9]))

>Reverse an array

In [59]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [70]:
x4 = np.random.randint(10, size=(4,4))

In [71]:
x4

array([[2, 0, 3, 2],
       [0, 7, 5, 9],
       [0, 2, 7, 2],
       [9, 2, 3, 3]])

In [72]:
x4[::-1], x4[:,::-1], x4[::-1,::-1]

(array([[9, 2, 3, 3],
        [0, 2, 7, 2],
        [0, 7, 5, 9],
        [2, 0, 3, 2]]),
 array([[2, 3, 0, 2],
        [9, 5, 7, 0],
        [2, 7, 2, 0],
        [3, 3, 2, 9]]),
 array([[3, 3, 2, 9],
        [2, 7, 2, 0],
        [9, 5, 7, 0],
        [2, 3, 0, 2]]))

In [73]:
x4.T

array([[2, 0, 0, 9],
       [0, 7, 2, 2],
       [3, 5, 7, 3],
       [2, 9, 2, 3]])

In [75]:
x4

array([[2, 0, 3, 2],
       [0, 7, 5, 9],
       [0, 2, 7, 2],
       [9, 2, 3, 3]])

In [76]:
x4[0], x4[0,:], x4[:,0]

(array([2, 0, 3, 2]), array([2, 0, 3, 2]), array([2, 0, 0, 9]))

# Reshaping Arrays

In [81]:
x2 = np.random.randint(10,size=(3,4))
x2

array([[9, 1, 4, 6],
       [8, 2, 3, 0],
       [0, 6, 0, 6]])

In [83]:
x2.reshape(4,3)

array([[9, 1, 4],
       [6, 8, 2],
       [3, 0, 0],
       [6, 0, 6]])

In [85]:
grid = np.arange(1, 10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

>Array to row vector

In [86]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [87]:
x.reshape((1,3))

array([[1, 2, 3]])

In [88]:
x[np.newaxis, :]

array([[1, 2, 3]])

>Array to column vector

In [89]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [90]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

In [91]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [92]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [93]:
np.concatenate([x,y,x])

array([1, 2, 3, 3, 2, 1, 1, 2, 3])

In [94]:
np.array([x,y])

array([[1, 2, 3],
       [3, 2, 1]])

In [95]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [97]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

>`vstack` and `hstack`

In [98]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

In [99]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [100]:
y = np.array([[99],[99]])
y

array([[99],
       [99]])

In [102]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

>Splitting arrays

In [103]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
x1, x2, x3 = np.split(x, [3,5])
print(x, x1, x2, x3)

[1, 2, 3, 99, 99, 3, 2, 1] [1 2 3] [99 99] [3 2 1]


In [107]:
upper, lower = np.vsplit(grid, [2])
print(f"Upper:\n {upper}")
print(f"Lower:\n {lower}")

Upper:
 [[0 1 2 3]
 [4 5 6 7]]
Lower:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [109]:
left, right = np.hsplit(grid, [2])
print(f"Left:\n{left}")
print(f"Right:\n{right}")

Left:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Array computation: Universal Functions

In [ ]:
import numpy as np 
np.random.seed(0)

>Slow calculations with regular CPython

In [ ]:
def compute_reciprocals(values): 
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [116]:
big_array = np.random.randint(1, 100, size=int(1e6))
%timeit compute_reciprocals(big_array)

1.2 s ± 17.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [117]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [119]:
%timeit (1.0 / big_array)

1.05 ms ± 15.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [122]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [123]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

>Arithmetic
>
>These are equivalent to, eg. `np.add()` or `np.divide()`

In [129]:
x = np.arange(4)
print(f"x + 5 \t= {x + 5}")
print(f"x - 5 \t= {x - 5}")
print(f"x * 2 \t= {x * 2}")
print(f"x / 2 \t= {x / 2}")
print(f"x // 2 \t= {x // 2}")
print(f"x ** 2 \t= {x ** 2}")
print(f"x % 2 \t= {x % 2}")

x + 5 	= [5 6 7 8]
x - 5 	= [-5 -4 -3 -2]
x * 2 	= [0 2 4 6]
x / 2 	= [0.  0.5 1.  1.5]
x // 2 	= [0 0 1 1]
x ** 2 	= [0 1 4 9]
x % 2 	= [0 1 0 1]


In [125]:
x - 5

array([-5, -4, -3, -2])

In [130]:
-(0.5*x + 1) **2

array([-1.  , -2.25, -4.  , -6.25])

>Absolute value
>can use `abs()` or `np.absolute()`, with an alias of `np.abs()`

In [131]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [132]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [133]:
np.absolute(x)

array([2, 1, 0, 1, 2])

> Absolute value of complex numbers returns magintude

In [134]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
x

array([3.-4.j, 4.-3.j, 2.+0.j, 0.+1.j])

In [135]:
np.abs(x)

array([5., 5., 2., 1.])

>Trigonometry

In [136]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [139]:
np.sin(theta), np.cos(theta), np.tan(theta)

(array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]),
 array([ 1.000000e+00,  6.123234e-17, -1.000000e+00]),
 array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16]))

In [140]:
x = [-1, 0, 1]
np.arcsin(x), np.arccos(x), np.arctan(x)

(array([-1.57079633,  0.        ,  1.57079633]),
 array([3.14159265, 1.57079633, 0.        ]),
 array([-0.78539816,  0.        ,  0.78539816]))

>Exponents and Logs

In [143]:
x = [1,2,3]
print(f"e^x:\t{np.exp(x)}")
print(f"2^x:\t{np.exp2(x)}")
print(f"3^x:\t{np.power(3, x)}")

e^x:	[ 2.71828183  7.3890561  20.08553692]
2^x:	[2. 4. 8.]
3^x:	[ 3  9 27]


In [146]:
x = [1, 2, 4, 10]
print(f"ln(x):\t{np.log(x)}")
print(f"log2(x):\t{np.log2(x)}")
print(f"log10(x):\t{np.log10(x)}")

ln(x):	[0.         0.69314718 1.38629436 2.30258509]
log2(x):	[0.         1.         2.         3.32192809]
log10(x):	[0.         0.30103    0.60205999 1.        ]


>[!attention]
>For maintaining precision with very small input, instead use:

In [151]:
x = [0, 0.001, 0.01, 0.1, 1e-10]
print(f"exp(x) - 1 = {np.expm1(x)}")
print(f"log(1 + x) = {np.log1p(x)}")

exp(x) - 1 = [0.00000000e+00 1.00050017e-03 1.00501671e-02 1.05170918e-01
 1.00000000e-10]
log(1 + x) = [0.00000000e+00 9.99500333e-04 9.95033085e-03 9.53101798e-02
 1.00000000e-10]


>Specialized ufuncs with `scipy`

In [160]:
from scipy import special

In [163]:
x = [1, 5, 10]

>Gamma functions

In [164]:
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


> Error function (integral of Gaussian), its complement and inverse

In [165]:
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


>Aggregation: reduce and accumulate

In [166]:
x = np.arange(1,6)

In [171]:
np.add.reduce(x) # same as `np.sum()`

15

In [172]:
np.multiply.reduce(x) # same as `np.prod()`

120

In [173]:
np.add.accumulate(x) # same as `np.cumsum()`

array([ 1,  3,  6, 10, 15])

In [174]:
np.multiply.accumulate(x) # same as `np.cumprod`

array([  1,   2,   6,  24, 120])

>__Specifying pre-existing output array__
>
>for large calculations, avoids creation of a temporary array with a subsequent copy into y

In [176]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [177]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


>Perform calculations on pairs with `outer`

In [181]:
x = np.arange(1, 6)
np.multiply(x,x)

array([ 1,  4,  9, 16, 25])

In [182]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [183]:
np.add.outer(x,x)

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

# Statistical Aggregation

In [184]:
import numpy as np 
L = np.random.random(100)

>Summing

In [185]:
np.sum(L)

49.210421685435314

In [187]:
big_array = np.random.rand(int(1e6))
%timeit sum(big_array)
%timeit np.sum(big_array)

57.2 ms ± 1.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
245 μs ± 19.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


>Minimum and Maximum

In [189]:
np.min(big_array), np.max(big_array)

(2.067514368597756e-07, 0.9999992772471815)

In [190]:
%timeit min(big_array)
%timeit np.min(big_array)

41.4 ms ± 621 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
167 μs ± 1.87 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


>Alternate syntax

In [191]:
big_array.sum(), big_array.max()

(499859.51691425196, 0.9999992772471815)

>Multidemensional aggregates